### ISSUE TITLE
Tag HTML redundante en string

### ISSUE THREAD

**Issue by mrleemon** [joseconti/woo-redsys-gateway-light#22]
En la siguiente línea, el tag HTML `<code></code>` está duplicado:

https://github.com/joseconti/woo-redsys-gateway-light/blob/d1052111fd815b2bddd8e41886ed8efcf6daa4d8/classes/class-wc-gateway-redsys.php#L291

**Comment by joseconti** [comment]
Muchas gracias,

Arreglado https://github.com/joseconti/woo-redsys-gateway-light/commit/220eb4af57b206393e867cd27e111a8af0d2105c
