### ISSUE TITLE
esc_html__ no es necesario

### ISSUE THREAD

**Issue by mrleemon** [joseconti/woo-redsys-gateway-light#33]
En la siguiente línea se escapa el html de los enlaces y por tanto no se ven correctamente cuando se visita la página de configuración de la pasarela Bizum Lite:

https://github.com/joseconti/woo-redsys-gateway-light/blob/0bec1c0008940dd26c11d51be6921b9d503c9752/classes/class-wc-gateway-bizum-redsys.php#L361

Habría que cambiar la función `esc_html__` por una simple `__`

**Comment by joseconti** [comment]
Hola,

En la realidad siempre hay que espacar, pero y lo he corregido para que lo haga con la forma correcta, que es con kses. Ya lo había cambiado en redirección, pero me dejé Biuzm. Saldrá en la siguiente versión.

https://github.com/joseconti/woo-redsys-gateway-light/commit/43062d223633d778b328a8badd0183b20264edc9

Saludos y muchas gracias
